'use client';
import { useEffect, useState } from 'react';
import { CalendarClock } from 'lucide-react';
import { upcomingSchedule, type Trip } from '@/lib/scheduled-time';
const color=(v:string,f:string)=>/^#[0-9a-f]{6}$/i.test(v)?v:f;
const scheduledEta=(minutes:number)=>minutes<1?'τώρα':Math.ceil(minutes)+'′';
export function ScheduledArrivals({stop,line,direction,now,enabled,compact=false}:{stop:string;line:string;direction:string;now:number;enabled:boolean;compact?:boolean}){
 const [trips,setTrips]=useState<Trip[]>([]),[state,setState]=useState('loading');
 const day=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Athens',weekday:'short'}).format(new Date(now)));
 useEffect(()=>{setTrips([]);if(!enabled)return;const controller=new AbortController();let loading=false;const load=async()=>{if(document.hidden||loading)return;loading=true;try{const data=await Promise.all([day,(day+1)%7].map(async d=>{const r=await fetch('/api/bus?kind=schedule&code='+stop+'&day='+d,{signal:controller.signal});if(!r.ok)throw Error('schedule');const raw=await r.json();if(!Array.isArray(raw))throw Error('schedule');return raw.filter((t:Trip)=>t.stopCode===stop).map((t:Trip)=>({...t,day:d}))}));if(!controller.signal.aborted){setTrips(data.flat());setState('ready')}}catch(e:any){if(e.name!=='AbortError')setState('error')}finally{loading=false}};setState('loading');void load();const interval=setInterval(load,60000);const visible=()=>{if(!document.hidden)void load()};document.addEventListener('visibilitychange',visible);return()=>{controller.abort();clearInterval(interval);document.removeEventListener('visibilitychange',visible)}},[stop,day,enabled]);
 if(!enabled)return null;const upcoming=upcomingSchedule(trips,now,line,direction);if(compact){const trip=upcoming[0];return <div className="scheduled-compact"><CalendarClock size={15}/>{state!=='ready'?<span>{state==='loading'?'Φόρτωση προγράμματος…':'Πρόγραμμα μη διαθέσιμο'}</span>:trip?<><span>{trip.lineCode} · Εκτιμώμενη άφιξη · πρόγραμμα {trip.tripTime}</span><strong>{scheduledEta(trip.minutes)}</strong></>:<span>Χωρίς δρομολόγιο στα επόμενα 45′</span>}</div>}
 return <section className="scheduled-arrivals" aria-label="Προγραμματισμένες αφίξεις"><div className="scheduled-arrivals-heading"><CalendarClock size={16}/><span>Πρόγραμμα · επόμενα 45′</span></div>{state==='loading'?<p>Φόρτωση προγράμματος…</p>:state==='error'?<p>Το πρόγραμμα δεν είναι διαθέσιμο αυτή τη στιγμή.</p>:!upcoming.length?<p>Δεν υπάρχουν προγραμματισμένες διελεύσεις στα επόμενα 45′.</p>:upcoming.map((t,i)=><div className="arrival-card scheduled-card" key={t.day+'-'+t.id+'-'+i}><span className="line-badge" style={{background:color(t.lineColor,'#657075'),color:color(t.lineTextColor,'#fff')}}>{t.lineCode}</span><span className="route-name">{t.routeName}<small><CalendarClock size={12}/>Προγραμματισμένη · {t.tripTime}</small></span><span className="eta">{scheduledEta(t.minutes)}<small>{t.minutes<1?'πρόγραμμα':Math.ceil(t.minutes)===1?'λεπτό':'λεπτά'}</small></span></div>)}<p className="scheduled-arrivals-note">Ώρες προγράμματος, όχι ζωντανή θέση. Μόλις εμφανιστεί live λεωφορείο, προβάλλεται η τηλεματική.</p></section>
}
